Fix test name filtering, improve CI code (#16)

diff --git a/.github/workflows/test-unit.yml b/.github/workflows/test-unit.yml
--- a/.github/workflows/test-unit.yml
+++ b/.github/workflows/test-unit.yml
@@ -79,14 +79,16 @@ jobs:
         id: test
         continue-on-error: true
         run: |
-          go test -short -coverprofile=unit.coverprofile -covermode=atomic -race -json ./... | go run . -progress -store test-report.jsonl -skip-report -failed-tests failed1.txt -
-          # retry 1, run tests if failed1.txt exists, pass otherwise
-          test ! -f failed1.txt || (echo "Retry 1" && go test -short -race -run $(cat failed1.txt) -json ./... | go run . -progress -store test-report2.jsonl -skip-report -failed-tests failed2.txt -)
-          # retry 2, run tests if failed2.txt exists, pass otherwise
-          test ! -f failed2.txt || (echo "Retry 2" && go test -short -race -run $(cat failed2.txt) -json ./... | go run . -progress -store test-report3.jsonl -skip-report -failed-tests failed3.txt -)
-          # retry 3, run tests if failed3.txt exists, pass otherwise
-          test ! -f failed3.txt || (echo "Retry 3" && go test -short -race -run $(cat failed3.txt) -json ./... | go run . -progress -store test-report4.jsonl -skip-report -failed-tests failed4.txt -)
+          # First run.
+          go test -short -coverprofile=unit.coverprofile -covermode=atomic -race -json ./... | go run . -progress -store test-report0.jsonl -skip-report -failed-tests failed.txt -
 
+          # Retries.
+          for i in {1..3}
+          do
+          test ! -f failed.txt || (export FAILED=$(cat failed.txt) && rm failed.txt && echo "Retry $i: $FAILED" && go test -short -race -run $FAILED -json ./... | go run . -progress -store test-report${i}.jsonl -skip-report -failed-tests failed.txt -)
+          done
+
+          # Reporting.
           REPORT=$(go run . -markdown test-report*.jsonl)
           echo "${REPORT}"
           echo "report<<EOF" >> $GITHUB_OUTPUT && echo "$REPORT" >> $GITHUB_OUTPUT && echo "EOF" >> $GITHUB_OUTPUT
@@ -94,8 +96,8 @@ jobs:
           TOTAL=$(grep 'total:' unit.txt)
           echo "${TOTAL}"
           echo "total=$TOTAL" >> $GITHUB_OUTPUT
-          test ! -f failed4.txt || echo "Tests failed after 4 retries"
-          test ! -f failed4.txt || (echo "failed=true" >> $GITHUB_OUTPUT)
+          test ! -f failed.txt || echo "Tests failed after retries"
+          test ! -f failed.txt || (echo "failed=true" >> $GITHUB_OUTPUT)
 
       - name: Test report
         uses: actions/upload-artifact@v3
