No coverage on retry

diff --git a/.github/workflows/test-unit.yml b/.github/workflows/test-unit.yml
--- a/.github/workflows/test-unit.yml
+++ b/.github/workflows/test-unit.yml
@@ -81,11 +81,11 @@ jobs:
         run: |
           go test -short -coverprofile=unit.coverprofile -covermode=atomic -race -json ./... | go run . -progress -store test-report.jsonl -skip-report -failed-tests failed1.txt -
           # retry 1, run tests if failed1.txt exists, pass otherwise
-          test ! -f failed1.txt || echo "Retry 1" && go test -short -coverprofile=unit.coverprofile -covermode=atomic -race -run $(cat failed1.txt) -json ./... | go run . -progress -store test-report2.jsonl -skip-report -failed-tests failed2.txt -
+          test ! -f failed1.txt || echo "Retry 1" && go test -short -race -run $(cat failed1.txt) -json ./... | go run . -progress -store test-report2.jsonl -skip-report -failed-tests failed2.txt -
           # retry 2, run tests if failed2.txt exists, pass otherwise
-          test ! -f failed2.txt || echo "Retry 2" && go test -short -coverprofile=unit.coverprofile -covermode=atomic -race -run $(cat failed2.txt) -json ./... | go run . -progress -store test-report3.jsonl -skip-report -failed-tests failed3.txt -
+          test ! -f failed2.txt || echo "Retry 2" && go test -short -race -run $(cat failed2.txt) -json ./... | go run . -progress -store test-report3.jsonl -skip-report -failed-tests failed3.txt -
           # retry 3, run tests if failed2.txt exists, pass otherwise
-          test ! -f failed3.txt || echo "Retry 3" && go test -short -coverprofile=unit.coverprofile -covermode=atomic -race -run $(cat failed3.txt) -json ./... | go run . -progress -store test-report4.jsonl -skip-report -failed-tests failed4.txt -
+          test ! -f failed3.txt || echo "Retry 3" && go test -short -race -run $(cat failed3.txt) -json ./... | go run . -progress -store test-report4.jsonl -skip-report -failed-tests failed4.txt -
 
           REPORT=$(go run . -markdown test-report*.jsonl)
           echo "${REPORT}"
