Update CI and deps

diff --git a/.github/workflows/test-unit.yml b/.github/workflows/test-unit.yml
--- a/.github/workflows/test-unit.yml
+++ b/.github/workflows/test-unit.yml
@@ -66,12 +66,37 @@ jobs:
 
       - name: Test
         id: test
+        continue-on-error: true
         run: |
-          make test-unit
+          # First run.
+          go test -short -coverprofile=unit.coverprofile -covermode=atomic -race -json ./... 2>&1 | go run . -progress -store test-report0.jsonl -skip-report -failed-tests failed.txt -failed-builds errors.txt -
+
+          # Retries.
+          for i in {1..3}
+          do
+          test ! -f failed.txt || (export FAILED=$(cat failed.txt) && rm failed.txt && echo "Retry $i: $FAILED" && go test -short -race -run $FAILED -json ./... 2>&1 | go run . -progress -store test-report${i}.jsonl -skip-report -failed-tests failed.txt -)
+          done
+
+          # Reporting.
+          REPORT=$(go run . -failure-stats failure-stats.txt -markdown test-report*.jsonl)
+          echo "${REPORT}"
+          
+          test ! -f failed.txt || echo "Tests failed after retries: $(cat failed.txt)" 1>&2
+          test ! -f failed.txt || (echo "failed=true" >> $GITHUB_OUTPUT)
+          test ! -f errors.txt || (echo "failed=true" >> $GITHUB_OUTPUT)
+
+          echo "failure-stats<<EOF" >> $GITHUB_OUTPUT && cat failure-stats.txt >> $GITHUB_OUTPUT && echo "EOF" >> $GITHUB_OUTPUT
+          echo "report<<EOF" >> $GITHUB_OUTPUT && echo "$REPORT" >> $GITHUB_OUTPUT && echo "EOF" >> $GITHUB_OUTPUT
           go tool cover -func=./unit.coverprofile > unit.txt
           TOTAL=$(grep 'total:' unit.txt)
           echo "${TOTAL}"
           echo "total=$TOTAL" >> $GITHUB_OUTPUT
+
+      - name: Test report
+        uses: actions/upload-artifact@v3
+        with:
+          name: test-report
+          path: test-report.jsonl
 
       - name: Annotate missing test coverage
         id: annotate
@@ -104,12 +129,18 @@ jobs:
             <details><summary>Coverage of changed lines</summary>
             
             ${{ steps.annotate.outputs.rep }}
-
+            
             </details>
 
             <details><summary>Coverage diff with base branch</summary>
-
+            
             ${{ steps.annotate.outputs.diff }}
+            
+            </details>
+            
+            <details><summary>Test stats: ${{ steps.test.outputs.failure-stats }}</summary>
+            
+            ${{ steps.test.outputs.report }}
             
             </details>
 
@@ -123,3 +154,9 @@ jobs:
         with:
           files: ./unit.coverprofile
           flags: unittests
+
+      - name: Check test result
+        if: steps.test.outputs.failed == 'true'
+        run: |
+          echo "::error ::Test failed, see Test step for details"
+          exit 1
