Keep test name separate

diff --git a/.github/workflows/test-imperfect.yml b/.github/workflows/test-imperfect.yml
--- a/.github/workflows/test-imperfect.yml
+++ b/.github/workflows/test-imperfect.yml
@@ -152,6 +152,8 @@ jobs:
           file: ./unit.coverprofile
           flags: unittests
 
-      - name: Check failure
-        if: ${{ steps.test.outputs.failed }} == "true"
-        run: exit 1
+      - name: Check test result
+        if: steps.test.outputs.failed == 'true'
+        run: |
+          echo "::error ::Test failed, see Test step for details"
+          exit 1
