Keep test name separate

diff --git a/.github/workflows/test-imperfect.yml b/.github/workflows/test-imperfect.yml
--- a/.github/workflows/test-imperfect.yml
+++ b/.github/workflows/test-imperfect.yml
@@ -77,11 +77,11 @@ jobs:
         run: |
           go test -tags imperfect -short -coverprofile=unit.coverprofile -covermode=atomic -race -json ./... | go run . -progress -store test-report.jsonl -skip-report -failed-tests failed1.txt -
           # retry 1, run tests if failed1.txt exists, pass otherwise
-          test ! -f failed1.txt || echo "Retry 1" && cat failed1.txt && go test -tags imperfect -short -race -run $(cat failed1.txt) -json ./... | go run . -progress -store test-report2.jsonl -skip-report -failed-tests failed2.txt -
+          test ! -f failed1.txt || (echo "Retry 1" && cat failed1.txt && go test -tags imperfect -short -race -run $(cat failed1.txt) -json ./... | go run . -progress -store test-report2.jsonl -skip-report -failed-tests failed2.txt -)
           # retry 2, run tests if failed2.txt exists, pass otherwise
-          test ! -f failed2.txt || echo "Retry 2" && cat failed2.txt && go test -tags imperfect -short -race -run $(cat failed2.txt) -json ./... | go run . -progress -store test-report3.jsonl -skip-report -failed-tests failed3.txt -
+          test ! -f failed2.txt || (echo "Retry 2" && cat failed2.txt && go test -tags imperfect -short -race -run $(cat failed2.txt) -json ./... | go run . -progress -store test-report3.jsonl -skip-report -failed-tests failed3.txt -)
           # retry 3, run tests if failed3.txt exists, pass otherwise
-          test ! -f failed3.txt || echo "Retry 3" && cat failed3.txt && go test -tags imperfect -short -race -run $(cat failed3.txt) -json ./... | go run . -progress -store test-report4.jsonl -skip-report -failed-tests failed4.txt -
+          test ! -f failed3.txt || (echo "Retry 3" && cat failed3.txt && go test -tags imperfect -short -race -run $(cat failed3.txt) -json ./... | go run . -progress -store test-report4.jsonl -skip-report -failed-tests failed4.txt -)
 
           REPORT=$(go run . -markdown test-report*.jsonl)
           echo "${REPORT}"
@@ -91,7 +91,7 @@ jobs:
           echo "${TOTAL}"
           echo "total=$TOTAL" >> $GITHUB_OUTPUT
           test ! -f failed4.txt || echo "Tests failed after 4 retries"
-          test ! -f failed4.txt || echo "failed=true" >> $GITHUB_OUTPUT
+          test ! -f failed4.txt || (echo "failed=true" >> $GITHUB_OUTPUT)
 
       - name: Test report
         uses: actions/upload-artifact@v3
