Add test that could not be built

diff --git a/.github/workflows/test-broken.yml b/.github/workflows/test-broken.yml
--- a/.github/workflows/test-broken.yml
+++ b/.github/workflows/test-broken.yml
@@ -1,5 +1,5 @@
 # This script is provided by github.com/bool64/dev.
-name: test-imperfect
+name: test-broken
 on:
   pull_request:
 
@@ -76,12 +76,12 @@ jobs:
         continue-on-error: true
         run: |
           # First run.
-          go test -tags imperfect -short -coverprofile=unit.coverprofile -covermode=atomic -race -json ./... |& go run . -progress -store test-report0.jsonl -skip-report -failed-tests failed.txt -failed-builds errors.txt -
+          go test -tags broken -short -coverprofile=unit.coverprofile -covermode=atomic -race -json ./... |& go run . -progress -store test-report0.jsonl -skip-report -failed-tests failed.txt -failed-builds errors.txt -
           
           # Retries.
           for i in {1..20}
           do
-          test ! -f failed.txt || (export FAILED=$(cat failed.txt) && rm failed.txt && echo "Retry $i: $FAILED" && go test -tags imperfect -short -race -run $FAILED -json ./... |& go run . -progress -store test-report${i}.jsonl -skip-report -failed-tests failed.txt -)
+          test ! -f failed.txt || (export FAILED=$(cat failed.txt) && rm failed.txt && echo "Retry $i: $FAILED" && go test -tags broken -short -race -run $FAILED -json ./... |& go run . -progress -store test-report${i}.jsonl -skip-report -failed-tests failed.txt -)
           done
 
           # Reporting.
@@ -127,9 +127,9 @@ jobs:
         uses: marocchino/sticky-pull-request-comment@v2
         with:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          header: imperfect-test
+          header: broken-test
           message: |
-            ### Imperfect Test Coverage
+            ### Broken Test Coverage
             ${{ steps.test.outputs.total }}
             ${{ steps.annotate.outputs.total }}
             <details><summary>Coverage of changed lines</summary>
diff --git a/.github/workflows/test-unit.yml b/.github/workflows/test-unit.yml
--- a/.github/workflows/test-unit.yml
+++ b/.github/workflows/test-unit.yml
@@ -80,24 +80,27 @@ jobs:
         continue-on-error: true
         run: |
           # First run.
-          go test -short -coverprofile=unit.coverprofile -covermode=atomic -race -json ./... | go run . -progress -store test-report0.jsonl -skip-report -failed-tests failed.txt -
+          go test -short -coverprofile=unit.coverprofile -covermode=atomic -race -json ./... |& go run . -progress -store test-report0.jsonl -skip-report -failed-tests failed.txt -failed-builds errors.txt -
 
           # Retries.
           for i in {1..3}
           do
-          test ! -f failed.txt || (export FAILED=$(cat failed.txt) && rm failed.txt && echo "Retry $i: $FAILED" && go test -short -race -run $FAILED -json ./... | go run . -progress -store test-report${i}.jsonl -skip-report -failed-tests failed.txt -)
+          test ! -f failed.txt || (export FAILED=$(cat failed.txt) && rm failed.txt && echo "Retry $i: $FAILED" && go test -short -race -run $FAILED -json ./... |& go run . -progress -store test-report${i}.jsonl -skip-report -failed-tests failed.txt -)
           done
 
           # Reporting.
           REPORT=$(go run . -markdown test-report*.jsonl)
           echo "${REPORT}"
+          
+          test ! -f failed.txt || echo "Tests failed after retries: $(cat failed.txt)" 1>&2
+          test ! -f failed.txt || (echo "failed=true" >> $GITHUB_OUTPUT)
+          test ! -f errors.txt || (echo "failed=true" >> $GITHUB_OUTPUT)
+
           echo "report<<EOF" >> $GITHUB_OUTPUT && echo "$REPORT" >> $GITHUB_OUTPUT && echo "EOF" >> $GITHUB_OUTPUT
           go tool cover -func=./unit.coverprofile > unit.txt
           TOTAL=$(grep 'total:' unit.txt)
           echo "${TOTAL}"
           echo "total=$TOTAL" >> $GITHUB_OUTPUT
-          test ! -f failed.txt || echo "Tests failed after retries"
-          test ! -f failed.txt || (echo "failed=true" >> $GITHUB_OUTPUT)
 
       - name: Test report
         uses: actions/upload-artifact@v3
